sudo: required

services:
    - docker

before_install:
    - docker build -t amagdi65/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true amagdi65/docker-react npm run test -- --coverage