version: '3'
services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app2/node_modules
            - .:/app2
        stdin_open: true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app2/node_modules
            - .:/app2
        command: ["npm", "run", "test"]
